# GigGatek Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files to load
rule_files:
  - "rules/alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for server metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # MySQL exporter for database metrics
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
    
  # Redis exporter for cache metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Backend application metrics
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:5000']
    
  # Apache exporter for frontend metrics
  - job_name: 'apache'
    static_configs:
      - targets: ['apache-exporter:9117']

  # Cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
